# Generated by Django 3.0.4 on 2020-05-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20200510_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='preview_url',
            field=models.FileField(max_length=500, null=True, upload_to=''),
        ),
    ]
