# Generated by Django 3.0.4 on 2020-06-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20200530_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='isbn',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
