# Generated by Django 3.0.4 on 2020-06-17 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_media_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribermedia',
            name='max_download',
        ),
    ]
