# Generated by Django 3.0.4 on 2020-06-30 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_subscribermediareserve'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LibraryMediaTransaction',
        ),
    ]
