# Generated by Django 3.0.4 on 2020-07-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_auto_20200708_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribermedia',
            name='expiration_time',
            field=models.DateTimeField(),
        ),
    ]
