# Generated by Django 3.0.4 on 2020-07-17 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_publisherstoragetransactions'),
        ('media', '0010_auto_20200716_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarymedia',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_media', to='users.Library'),
        ),
    ]
