# Generated by Django 3.0.4 on 2022-07-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_auto_20200717_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
