# Generated by Django 3.0.4 on 2022-07-11 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0012_media_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribermediatransaction',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_subscriber_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
