# Generated by Django 3.1.5 on 2022-07-17 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0014_librarymedia_rental_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribermedia',
            name='library_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_library_media', to='media.librarymedia'),
        ),
    ]
