# Generated by Django 3.1.5 on 2022-07-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0015_subscribermedia_library_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='main_category',
            field=models.CharField(choices=[('public', 'Public'), ('university/college', 'University/College'), ('secondary school', 'Secondary School'), ('primary school', 'Primary School'), ('kindergarten', 'Kindergarten')], max_length=100, null=True),
        ),
    ]
