# Generated by Django 3.0.4 on 2022-07-22 07:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0016_media_main_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarymedia',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 22, 7, 2, 40, 412330, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='librarymedia',
            name='media_library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renew_from', to='media.LibraryMedia'),
        ),
        migrations.AddField(
            model_name='librarymedia',
            name='transaction_type',
            field=models.CharField(choices=[('new', 'New'), ('renew', 'Renew')], default='new', max_length=10),
        ),
    ]
