# Generated by Django 3.0.4 on 2022-07-22 07:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0017_auto_20220722_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarymedia',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 22, 7, 26, 52, 845478, tzinfo=utc)),
        ),
    ]
