# Generated by Django 3.0.4 on 2022-07-22 07:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0018_auto_20220722_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarymedia',
            name='is_renew',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='librarymedia',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 22, 7, 35, 39, 44755, tzinfo=utc)),
        ),
    ]
