# Generated by Django 3.0.4 on 2022-07-22 10:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0019_auto_20220722_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarymedia',
            name='is_renew',
        ),
        migrations.RemoveField(
            model_name='librarymedia',
            name='transaction_type',
        ),
        migrations.AlterField(
            model_name='librarymedia',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 22, 10, 43, 13, 375389, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='librarymedia',
            name='media_library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_library_media', to='media.LibraryMedia'),
        ),
    ]
