# Generated by Django 3.1.5 on 2022-07-24 14:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0020_auto_20220722_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarymedia',
            name='is_renew',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='librarymedia',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 14, 48, 48, 578651, tzinfo=utc)),
        ),
    ]
