# Generated by Django 3.1.5 on 2022-07-24 14:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0021_auto_20220724_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarymedia',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 14, 57, 4, 562942, tzinfo=utc)),
        ),
    ]
