# Generated by Django 3.1.5 on 2022-07-25 09:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0023_auto_20220725_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarymedia',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 9, 7, 30, 686768, tzinfo=utc)),
        ),
    ]
