# Generated by Django 3.1.5 on 2022-07-25 09:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0024_auto_20220725_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarymedia',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 9, 35, 25, 757450, tzinfo=utc)),
        ),
    ]
