# Generated by Django 3.1.5 on 2022-08-01 03:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0025_auto_20220725_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarymedia',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 3, 48, 40, 50807, tzinfo=utc)),
        ),
    ]
