# Generated by Django 3.1.5 on 2022-08-05 06:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0027_auto_20220801_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarymedia',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 6, 54, 0, 551266, tzinfo=utc)),
        ),
    ]
