# Generated by Django 3.1.5 on 2022-08-09 09:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0028_auto_20220805_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarymedia',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 9, 41, 59, 391991, tzinfo=utc)),
        ),
    ]
