# Generated by Django 3.0.4 on 2022-09-06 06:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0029_auto_20220809_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarymedia',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 6, 53, 41, 333216, tzinfo=utc)),
        ),
    ]
