# Generated by Django 3.0.4 on 2020-06-02 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherNotesDownloaded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=100, null=True)),
                ('file_type', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('created_date', models.CharField(max_length=100)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Teacher_notes_downloaded',
            },
        ),
        migrations.CreateModel(
            name='TeacherNotesAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('action', models.CharField(choices=[('downloaded', 'Downloaded'), ('return', 'Return')], max_length=50)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_notes_action', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Teacher_notes_action',
            },
        ),
    ]
