# Generated by Django 3.0.4 on 2020-06-02 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teachernotesaction',
            table='teacher_notes_action',
        ),
        migrations.AlterModelTable(
            name='teachernotesdownloaded',
            table='teacher_notes_downloaded',
        ),
    ]
