# Generated by Django 3.0.4 on 2020-06-06 03:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher_notes', '0002_auto_20200602_0849'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherNotesDownloaded',
            new_name='NotesDownloaded',
        ),
        migrations.RenameField(
            model_name='notesdownloaded',
            old_name='teacher',
            new_name='subscriber',
        ),
        migrations.RenameField(
            model_name='teachernotesaction',
            old_name='teacher',
            new_name='subscriber',
        ),
    ]
