# Generated by Django 3.0.4 on 2020-06-06 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_notes', '0003_auto_20200606_0358'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notesdownloaded',
            table='teacher_notes_subscriber_downloaded',
        ),
        migrations.AlterModelTable(
            name='teachernotesaction',
            table='teacher_notes_subscriber_action',
        ),
    ]
