# Generated by Django 3.0.4 on 2020-06-07 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher_notes', '0004_auto_20200606_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesdownloaded',
            name='teacher',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_notes_teacher', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notesdownloaded',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_notes_subscriber', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teachernotesaction',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_notes_subscriber_action', to=settings.AUTH_USER_MODEL),
        ),
    ]
