# Generated by Django 3.0.4 on 2020-07-10 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher_notes', '0005_auto_20200607_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200)),
                ('size', models.IntegerField(default=0)),
                ('file_type', models.CharField(choices=[('folder', 'Folder'), ('file', 'File')], max_length=20)),
                ('url', models.CharField(max_length=10000)),
                ('parent_folder', models.IntegerField(default=0)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_notes',
            },
        ),
        migrations.CreateModel(
            name='TeacherNotesTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('action', models.CharField(choices=[('downloaded', 'Downloaded'), ('returned', 'Returned')], max_length=20)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_transaction', to='teacher_notes.TeacherNotes')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_transaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_notes_transaction',
            },
        ),
        migrations.CreateModel(
            name='TeacherNotesDownloaded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_downloaded', to='teacher_notes.TeacherNotes')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_downloaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_notes_downloaded',
            },
        ),
    ]
