# Generated by Django 3.0.4 on 2020-07-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_notes', '0006_teachernotes_teachernotesdownloaded_teachernotestransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachernotes',
            name='file_type',
            field=models.CharField(max_length=30),
        ),
    ]
