# Generated by Django 3.0.4 on 2020-05-09 00:10

import click.school_history.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, max_length=10000000, null=True)),
                ('photo', models.ImageField(null=True, upload_to=click.school_history.models.school_history_directory_path)),
                ('is_active', models.BooleanField(default=True)),
                ('publish_date', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_school_histories', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_school_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sh_school_history',
            },
        ),
    ]
