# Generated by Django 3.0.4 on 2020-05-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='number_of_subscribers',
        ),
        migrations.AddField(
            model_name='library',
            name='max_subscribers',
            field=models.IntegerField(default=100),
        ),
    ]
