# Generated by Django 3.0.4 on 2020-06-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200607_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='storage',
            field=models.FloatField(default=1.0),
        ),
    ]
