# Generated by Django 3.0.4 on 2020-06-17 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_publisher_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherStorageTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('buy_storage', models.FloatField(default=1.0)),
                ('status', models.CharField(choices=[('approve', 'Approve'), ('waiting', 'Waiting'), ('reject', 'Reject')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_storage_transaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_publisher_storage_transactions',
            },
        ),
    ]
