# Generated by Django 3.0.4 on 2020-06-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_publisherstoragetransactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='max_device',
            field=models.SmallIntegerField(default=2),
        ),
    ]
