# Generated by Django 3.0.4 on 2020-06-20 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200617_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_activity',
            },
        ),
    ]
