# Generated by Django 3.0.4 on 2020-06-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200628_0201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublisherStorageTransactions',
        ),
    ]
