# Generated by Django 3.0.4 on 2022-07-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_publisherstoragetransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarian',
            name='storage',
            field=models.FloatField(default=10.0),
        ),
    ]
