# Generated by Django 3.1.5 on 2022-08-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_librarian_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='storage',
            field=models.FloatField(default=0),
        ),
    ]
