# Generated by Django 3.0.4 on 2020-07-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmmedia',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='confirmstorage',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='requestmedia',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='requeststorage',
            name='data_upgrade',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='requeststorage',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], max_length=20),
        ),
    ]
