# Generated by Django 3.0.4 on 2022-07-04 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_auto_20200717_0341'),
        ('notification', '0002_auto_20200704_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagecontent',
            name='message_type',
            field=models.CharField(choices=[('request_storage', 'Request_storage'), ('request_delete_sub', 'Request_delete_sub'), ('confirm_delete_sub', 'Confirm_delete_sub'), ('request_delete_tea', 'Request_delete_tea'), ('confirm_delete_tea', 'Confirm_delete_tea'), ('request_media', 'Request_media'), ('confirm_storage', 'Confirm_storage'), ('confirm_media', 'Confirm_media'), ('confirm_upload', 'Confirm_upload')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationreceiver',
            name='notification_type',
            field=models.CharField(choices=[('request_storage', 'Request_storage'), ('request_delete_sub', 'Request_delete_sub'), ('confirm_delete_sub', 'Confirm_delete_sub'), ('request_delete_tea', 'Request_delete_tea'), ('confirm_delete_tea', 'Confirm_delete_tea'), ('request_media', 'Request_media'), ('confirm_storage', 'Confirm_storage'), ('confirm_media', 'Confirm_media'), ('confirm_upload', 'Confirm_upload')], max_length=20),
        ),
        migrations.CreateModel(
            name='RequestDeleteSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], max_length=20)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_delete_subscriber_notify', to='notification.NotificationReceiver')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_delete_subscriber', to='media.Media')),
            ],
            options={
                'db_table': 'notification_request_delete_subscriber',
            },
        ),
        migrations.CreateModel(
            name='ConfirmDeleteSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], max_length=20)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirm_delete_subscriber_notify', to='notification.NotificationReceiver')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirm_delete_subscriber', to='notification.RequestDeleteSubscriber')),
            ],
            options={
                'db_table': 'notification_confirm_delete_subscriber',
            },
        ),
    ]
