# Generated by Django 3.0.4 on 2022-07-04 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_publisherstoragetransactions'),
        ('notification', '0003_auto_20220704_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdeletesubscriber',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_delete_subscriber', to='users.Subscriber'),
        ),
    ]
