# Generated by Django 3.0.4 on 2022-07-04 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_publisherstoragetransactions'),
        ('notification', '0004_auto_20220704_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDeleteTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], max_length=20)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_delete_teacher_notify', to='notification.NotificationReceiver')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_delete_teacher', to='users.Teacher')),
            ],
            options={
                'db_table': 'notification_request_delete_teacher',
            },
        ),
        migrations.CreateModel(
            name='ConfirmDeleteTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], max_length=20)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirm_delete_teacher_notify', to='notification.NotificationReceiver')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirm_delete_teacher', to='notification.RequestDeleteTeacher')),
            ],
            options={
                'db_table': 'notification_confirm_delete_teacher',
            },
        ),
    ]
