# Generated by Django 3.0.4 on 2022-07-04 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_confirmdeleteteacher_requestdeleteteacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestdeleteteacher',
            old_name='subscriber',
            new_name='teacher',
        ),
    ]
