# Generated by Django 3.0.4 on 2022-07-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0011_auto_20220722_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationdetail',
            name='rental_period',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
