# Generated by Django 3.1.5 on 2022-07-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0013_requestrenewmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagecontent',
            name='message_type',
            field=models.CharField(choices=[('request_storage', 'Request_storage'), ('request_delete_sub', 'Request_delete_sub'), ('confirm_delete_sub', 'Confirm_delete_sub'), ('request_delete_tea', 'Request_delete_tea'), ('confirm_delete_tea', 'Confirm_delete_tea'), ('request_media', 'Request_media'), ('confirm_storage', 'Confirm_storage'), ('confirm_media', 'Confirm_media'), ('confirm_upload', 'Confirm_upload'), ('send_quotation', 'Send_quotation'), ('request_renew_media', 'Send_quotation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationreceiver',
            name='notification_type',
            field=models.CharField(choices=[('request_storage', 'Request_storage'), ('request_delete_sub', 'Request_delete_sub'), ('confirm_delete_sub', 'Confirm_delete_sub'), ('request_delete_tea', 'Request_delete_tea'), ('confirm_delete_tea', 'Confirm_delete_tea'), ('request_media', 'Request_media'), ('confirm_storage', 'Confirm_storage'), ('confirm_media', 'Confirm_media'), ('confirm_upload', 'Confirm_upload'), ('send_quotation', 'Send_quotation'), ('request_renew_media', 'Send_quotation')], max_length=20),
        ),
    ]
