# Generated by Django 3.1.5 on 2022-07-24 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0014_auto_20220724_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmRenewMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], max_length=20)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirm_renew_media', to='notification.notificationreceiver')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirm_renew_medias', to='notification.requestrenewmedia')),
            ],
            options={
                'db_table': 'notification_confirm_renew_media',
            },
        ),
    ]
