# Generated by Django 3.1.5 on 2022-07-25 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0016_auto_20220725_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagecontent',
            name='message_type',
            field=models.CharField(choices=[('request_storage', 'Request_storage'), ('request_delete_sub', 'Request_delete_sub'), ('confirm_delete_sub', 'Confirm_delete_sub'), ('request_delete_tea', 'Request_delete_tea'), ('confirm_delete_tea', 'Confirm_delete_tea'), ('request_media', 'Request_media'), ('confirm_storage', 'Confirm_storage'), ('confirm_media', 'Confirm_media'), ('confirm_renew_media', 'Confirm_renew_media'), ('confirm_upload', 'Confirm_upload'), ('send_quotation', 'Send_quotation'), ('request_renew_media', 'Send_quotation'), ('expired_media', 'Expired_media')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationreceiver',
            name='notification_type',
            field=models.CharField(choices=[('request_storage', 'Request_storage'), ('request_delete_sub', 'Request_delete_sub'), ('confirm_delete_sub', 'Confirm_delete_sub'), ('request_delete_tea', 'Request_delete_tea'), ('confirm_delete_tea', 'Confirm_delete_tea'), ('request_media', 'Request_media'), ('confirm_storage', 'Confirm_storage'), ('confirm_media', 'Confirm_media'), ('confirm_renew_media', 'Confirm_renew_media'), ('confirm_upload', 'Confirm_upload'), ('send_quotation', 'Send_quotation'), ('request_renew_media', 'Send_quotation'), ('expired_media', 'Expired_media')], max_length=20),
        ),
        migrations.CreateModel(
            name='ExpiredMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], max_length=20)),
                ('duration', models.CharField(blank=True, max_length=10, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_expired_media', to='notification.notificationreceiver')),
            ],
            options={
                'db_table': 'notification_expired_media',
            },
        ),
    ]
