# Generated by Django 3.1.5 on 2022-07-25 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0025_auto_20220725_1635'),
        ('notification', '0017_auto_20220725_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiredmedia',
            name='media_library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expired_media_library', to='media.librarymedia'),
        ),
    ]
