# Generated by Django 3.1.5 on 2022-08-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0019_sendquotation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendquotation',
            name='status',
        ),
    ]
