# Generated by Django 3.1.5 on 2022-08-05 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0020_remove_sendquotation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmmedia',
            name='status',
        ),
        migrations.RemoveField(
            model_name='confirmrenewmedia',
            name='status',
        ),
    ]
