# Generated by Django 3.1.5 on 2022-08-08 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0021_auto_20220805_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmdeleteteacher',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirm_delete_library_notify', to='notification.notificationreceiver'),
        ),
        migrations.AlterModelTable(
            name='confirmdeleteteacher',
            table='notification_confirm_delete_library',
        ),
        migrations.CreateModel(
            name='RequestDeleteLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], max_length=20)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_delete_library_notify', to='notification.notificationreceiver')),
            ],
            options={
                'db_table': 'notification_request_delete_library',
            },
        ),
        migrations.AlterField(
            model_name='confirmdeleteteacher',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirm_delete_library', to='notification.requestdeletelibrary'),
        ),
        migrations.DeleteModel(
            name='RequestDeleteTeacher',
        ),
    ]
