# Generated by Django 3.1.5 on 2022-08-08 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0022_auto_20220808_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestdeletelibrary',
            old_name='teacher',
            new_name='library',
        ),
    ]
