# Generated by Django 3.1.5 on 2022-08-08 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0023_auto_20220808_1534'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfirmDeleteTeacher',
            new_name='ConfirmDeleteLibrary',
        ),
    ]
