# Generated by Django 3.0.4 on 2020-05-09 00:11

import click.learning_material.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('duration', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('format_type', models.CharField(max_length=100, null=True)),
                ('media_type', models.CharField(choices=[('book', 'Book'), ('audio', 'Audio'), ('video', 'Video')], max_length=20, null=True)),
                ('number_of_download', models.IntegerField(default=0)),
                ('file_size', models.IntegerField(null=True)),
                ('url', models.FileField(upload_to=click.learning_material.models.learning_material_file_directory_path)),
                ('thumbnail', models.ImageField(null=True, upload_to='')),
                ('published_date', models.DateTimeField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_material_medias', to='master_data.Category')),
                ('library', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_material_media', to='users.Library')),
            ],
            options={
                'db_table': 'learning_material_media',
            },
        ),
        migrations.CreateModel(
            name='SubscriberMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_material_subscriber_medias', to='learning_material.Media')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_material_subscriber_medias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learning_material_media_subscriber',
            },
        ),
        migrations.CreateModel(
            name='MediaImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=click.learning_material.models.learning_material_image_directory_path)),
                ('thumbnail', models.ImageField(null=True, upload_to='')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='learning_material.Media')),
            ],
            options={
                'db_table': 'learning_material_media_image',
            },
        ),
    ]
