# Generated by Django 3.0.4 on 2020-06-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_material', '0002_subscribermediatransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='published_date',
            new_name='release_date',
        ),
        migrations.AddField(
            model_name='media',
            name='isbn',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
