# Generated by Django 3.1.5 on 2022-07-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_material', '0003_auto_20200619_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='main_category',
            field=models.CharField(choices=[('public', 'Public'), ('university/college', 'University/College'), ('secondary school', 'Secondary School'), ('primary school', 'Primary School'), ('kindergarten', 'Kindergarten')], max_length=100, null=True),
        ),
    ]
