# Generated by Django 3.1.5 on 2022-07-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_material', '0004_media_main_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='main_category',
            field=models.CharField(choices=[('Public', 'Public'), ('University/College', 'University/College'), ('Secondary School', 'Secondary School'), ('Primary School', 'Primary School'), ('Kindergarten', 'Kindergarten')], max_length=100, null=True),
        ),
    ]
