# Generated by Django 3.1.5 on 2022-08-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_material', '0005_auto_20220725_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='main_category',
            field=models.CharField(choices=[('Public', 'Public'), ('University/College', 'University/College'), ('Secondary School', 'Secondary School'), ('Primary School', 'Primary School'), ('Kindergarten', 'Kindergarten')], default='Public', max_length=100, null=True),
        ),
    ]
